# Version format
version: 0.1.{build}
skip_non_tags: true
init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        Update-AppveyorBuild -Version $env:APPVEYOR_REPO_TAG_NAME
      }
# Image with Python 3.12 support
image: Visual Studio 2022

# OPTIMIZATION: Disable default MSBuild & Test discovery (Saves ~1-2 mins)
build: off
test: off

environment:
  PYTHON: "C:\\Python312-x64"
  GITHUB_TOKEN:
    secure: "rnZoaKEmqLGJMMz8+cBkeypKvCSCgQ5HPJ+e6CY3W2f4WgrAUzLXx4QPQcJLeO01"
  GEMINI_API_KEY:
    secure: cqcmjgGM016vm/Xmrq8rPH6xHN58+fjAsY0nYZsJ2tMKBQ9+BGq8Wk5mASwLnh/t
  GEMINI_API_KEY_2:
    secure: bSiphxLRpQv+ubQMfZ12VLYjOqgIzbu5bg546sEMTVGJ1mTJVGy5Ep3MnVN7+Voh
  GEMINI_API_KEY_3:
    secure: V3M1NgNmHmQQr035vmCedhWMvWfq8opI57k4N/PhXR+Nplp4jpLmdaMekHKfAVNd
  NEW_RELIC_INSERT_KEY:
    secure: YGOEFnhdQrCY3+QccRFUMNp/+rwKXTXP89rHLjEp1u1lPiq8TbUa4JSsRglGtsTw
# OPTIMIZATION: Cache pip, but clear it if requirements.txt changes
# The arrow (->) tells AppVeyor: "If this file changes, delete the cache."
# Adding this line NOW effectively clears your old cache for the next build.
cache:
  - '%LOCALAPPDATA%\pip\Cache -> requirements.txt'

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -m pip install --upgrade pip setuptools wheel"

  # OPTIMIZATION: Inno Setup 6 is usually pre-installed on VS2022 image.
  # Commented out to save time. Uncomment if you get a "Path not found" error.
  - choco install innosetup --version=6.3.3 -y --no-progress

  # Install deps
  - "pip install --no-warn-script-location -r requirements.txt pypore3d --index-url https://pypi.org/simple/ --extra-index-url https://test.pypi.org/simple/"

build_script:
  - "python src/encrypt_env.py"
  - "pyinstaller --clean --noconfirm --log-level WARN --workpath build --distpath dist build.spec"
  - '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installers\pp3dg-setup.iss'

artifacts:
  - path: installers\*.exe
    name: WindowsInstaller

deploy:
  - provider: GitHub
    auth_token: $(GITHUB_TOKEN)
    artifact: WindowsInstaller
    draft: false
    prerelease: true
    force_update: true
    on:
      appveyor_repo_tag: true